version : '2'

services:
  ezrides-backend:
    extends: 
      file: backend/docker_workspace/docker-compose.yml
      service: ezrides-backend

  database: 
    extends:
      file: backend/docker-workspace/docker-compose.yml
      service: database

  ezrides-frontend:
    extends:
      file: frontend/docker-workspace/docker-compose.yml
      service: ezrides-front